# Generated by Django 3.0 on 2020-03-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200321_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='video_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
