# Generated by Django 3.0 on 2020-03-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_tutorial_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='video_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
