# Generated by Django 3.0 on 2020-03-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200321_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='video_url',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
