# Generated by Django 3.0 on 2020-03-23 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 12, 28, 10, 496273), verbose_name='date saved'),
        ),
        migrations.AlterField(
            model_name='status',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tutorial'),
        ),
    ]
