# Generated by Django 3.0.4 on 2020-03-23 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default='America/Denver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 15, 32, 44, 596075), verbose_name='date saved'),
        ),
    ]
