# Generated by Django 3.0.2 on 2020-03-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200323_1228'),
        ('main_app', '0012_auto_20200323_1025'),
    ]

    operations = [
    ]
