# Generated by Django 3.0.4 on 2020-03-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200323_1228'),
        ('main_app', '0014_auto_20200323_1548'),
        ('main_app', '0012_auto_20200323_1025'),
    ]

    operations = [
    ]
