# Generated by Django 3.0 on 2020-03-25 16:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0014_auto_20200324_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='rating',
        ),
        migrations.AlterField(
            model_name='status',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 10, 28, 0, 819676), verbose_name='date saved'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
