# Generated by Django 3.0.2 on 2020-03-24 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200324_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 17, 56, 1, 657556), verbose_name='date saved'),
        ),
    ]
