# Generated by Django 3.0.2 on 2020-03-25 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20200324_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 18, 17, 59, 801340), verbose_name='date saved'),
        ),
    ]
