# Generated by Django 3.0.2 on 2020-03-25 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_merge_20200325_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 12, 37, 22, 286772), verbose_name='date saved'),
        ),
    ]
