# Generated by Django 3.0.2 on 2020-03-25 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20200325_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 14, 20, 27, 721034), verbose_name='date saved'),
        ),
    ]
