# Generated by Django 3.0.2 on 2020-03-26 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20200325_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 17, 59, 5, 242939), verbose_name='date saved'),
        ),
    ]
