# Generated by Django 3.0.2 on 2020-03-27 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20200326_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='saved',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 18, 2, 39, 810664), verbose_name='date saved'),
        ),
    ]
