# Generated by Django 3.0.4 on 2020-03-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='stats',
            field=models.CharField(choices=[('S', 'Saved'), ('C', 'Completed'), ('I', 'Incompleted')], default='S', max_length=100),
        ),
    ]
